version: '1.0'

services:
  sbsm:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/sbsm:cached
    ports:
      - 9901:9901
    depends_on:
      - mysql
  mysql:
    image: mysql:lts
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: mru
      MYSQL_PASSWORD: 123
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:
