version: '3'

services:

  sbsm:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - .:/sbsm
    ports:
      - 9901:9901
    depends_on:
      - mysql

  mysql:
    image: mysql:lts
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - TZ=Asia/Shanghai
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:
