# Conversion to YAML from Properties formar report
# Warnings:
# - The yaml file had comments which are lost in the refactoring!
spring:
  application:
    name: sbsm
  datasource:
    url: jdbc:mysql://localhost:3306/sbsm
    username: root
    password: 123
    druid:
      initial-size: 1
      max-active: 20
      min-idle: 1
      max-wait: 10000
server:
  port: 9901
  servlet:
    context-path: /sbsm
jwt:
  header: "Authorization"
  tokenPrefix: "Bearer "
  secret: "mgrru-secret"
  exp: 10800000 #3小时