# Conversion to YAML from Properties formar report
# Warnings:
# - The yaml file had comments which are lost in the refactoring!
spring:
  application:
    name: sbsm
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sbsm?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 10000
      minimum-idle: 5
      maximum-pool-size: 20
server:
  port: 9901
  servlet:
    context-path: /sbsm
jwt:
  header: "Authorization"
  tokenPrefix: "Bearer "
  secret: "mgrru-secret"
  exp: 10800000 #3小时
logging:
  level:
    web: DEBUG