version: '1.0'

services:
  sbsm:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace/sbsm:cached
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 9901:9901
    depends_on:
      - mysql
    command: /bin/bash -c "while sleep 1000; do :; done"

  mysql:
    image: ghcr.io/mgrru/mysql:lts
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_USER=mru
      - MYSQL_PASSWORD=1234
      - TZ=Asia/Shanghai
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  mysql:
